### PR TITLE
Fix 165

### LINKED ISSUE #165: CIDR Block Notation on Origin Type
Hello, so I need to whitelist a large group of IP addresses and to do that I'm using CIDR notation. I've already made the changes but I used a library from Apache to do most of the work. Is this allowed in this repository? The class I used can be found here 
http://svn.apache.org/repos/asf/commons/_moved_to_git/net/trunk/src/main/java/org/apache/commons/net/util/SubnetUtils.java

### PR DESCRIPTION
**Pull request by andrew-holman**
Fixes #165 

#### Changes proposed in this pull request:
 - Allows CIDR notation on the origin type to rate limit a group of IP addresses.
 - A few small fixes to my previous unit tests.

### CODE REVIEW

**Comment by andrew-holman** [comment]
I wasn't sure if it would be better to import the entire library or only include the one class. I chose to just add the class but let me know if you'd prefer me to import the library instead.

**Comment by marcosbarbero** [comment]
Hi @andrew-holman, I think adding the library is better because if there's any updates or fixes we can just update the library instead of copying the code every time, it can get lost at some point.

**Comment by andrew-holman** [comment]
Let me know if that change looks good. I also had to limit the unit tests I made because it kept giving me null headers whenever I used specific IP addresses. Do you know if there is a good way to fix this?

**Comment by andrew-holman** [comment]
Have you had a chance to checkout the changes I made to add the library?

**Comment by marcosbarbero** [comment]
Hi @andrew-holman I tried but turns out the new tests are not exactly running as expected, I'm trying to fix them before releasing it

**Comment by andrew-holman** [comment]
Oh, sorry about that I'll see if I get them to work.

**Comment by andrew-holman** [comment]
It seems that the key values are getting messed up by specifying the origin. It can be fixed by adjusting the key values for the tests that are supposed to use the white listed IP addresses. I'm not sure if this is a great fix because for future tests this could still come up as an issue. I think it could be fixed by adjusting how the key values are created but I don't know where that is or if we would want to mess with that for this change.

**Comment by marcosbarbero** [comment]
Hi @andrew-holman I'll work on that tomorrow and finally release this feature, sorry for the delay

**Comment by marcosbarbero** [comment]
Hi @andrew-holman your changes are included on [v2.2.4.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v2.2.4.RELEASE)
Just a heads up this change is not included on `1.7.x` line if you need that please let me know.

**Comment by andrew-holman** [comment]
Okay perfect thanks so much, I will need this change on 1.7.x. If you could do it that would be great, but I can also create another pull request if that is any easier for you.

**Pull request merged**
