### PR TITLE
Fix 165 1.7.x Loss of Code Coverage

### PR DESCRIPTION
**Pull request by andrew-holman**
Changes proposed in this pull request:
 - Added two test cases to bring the code coverage back up after the Fix 165 1.7.x pull request.

### CODE REVIEW

**Comment by andrew-holman** [comment]
Great, thanks for merging that! Do you know when you'll be releasing 1.7.4?

**Comment by marcosbarbero** [comment]
Hi @andrew-holman I'd a bad time trying to release this version, for some reason in the maven deploy phase it was breaking. 

However, I'm happy to tell (after some adjustments) the maven deploy succeed! In a couple of hours, the artifact should be available on maven central.

**Comment by andrew-holman** [comment]
Thanks so much @marcosbarbero, I really appreciate all the help with these pull requests.

**Comment by marcosbarbero** [comment]
Thank you for all the PR!

**Pull request merged**
