### PR TITLE
#45 Storage service downgrade - protect from any error with storage c…

### PR DESCRIPTION
**Pull request by lchayoun**
…onnection

### CODE REVIEW

**Comment by lchayoun** [comment]
@marcosbarbero I agree the behavior should enable customization by the user.
WDYT about this implementation?

**Comment by marcosbarbero** [comment]
I was wondering if you want to receive notifications from `travis build`. 
If you do please add your email to the `notifications.email` list in the `.travis.yml` file.

**Comment by lchayoun** [comment]
@marcosbarbero done 👍

**Comment by marcosbarbero** [comment]
@lchayoun do you think you'll be able to raise the code coverage to the same rate it was before? Let me know, it's quite good now but our checks as complaining 😄

**Comment by lchayoun** [comment]
@marcosbarbero I'll add some more tests :)

**Comment by marcosbarbero** [comment]
Nice!

**Comment by lchayoun** [comment]
@marcosbarbero Thanks, need your approval on this PR :)

**Pull request merged**
