### PR TITLE
Fix 165 for 1.7.x

### LINKED ISSUE #165: CIDR Block Notation on Origin Type
Hello, so I need to whitelist a large group of IP addresses and to do that I'm using CIDR notation. I've already made the changes but I used a library from Apache to do most of the work. Is this allowed in this repository? The class I used can be found here 
http://svn.apache.org/repos/asf/commons/_moved_to_git/net/trunk/src/main/java/org/apache/commons/net/util/SubnetUtils.java

### PR DESCRIPTION
**Pull request by andrew-holman**
Fixes #165 for branch 1.7.x

#### Changes proposed in this pull request:
 - Implemented changes in #166 to 1.7.x branch.

### CODE REVIEW

**Comment by andrew-holman** [comment]
@marcosbarbero, have you gotten a chance to look at this?

**Comment by marcosbarbero** [comment]
@andrew-holman could you follow up? The code coverage seems to have dropped https://coveralls.io/builds/24704870

**Comment by andrew-holman** [comment]
@marcosbarbero of course, I'll get on that right away. Did the code coverage only drop in the 1.7.x branch or was it an issue with the master branch as well?

**Comment by marcosbarbero** [comment]
It dropped on master as well but I remember I'd it fixed before releasing.

**Comment by andrew-holman** [comment]
Okay, this should be resolved in #183

**Pull request merged**
