### PR TITLE
added spring data tests

### PR DESCRIPTION
**Pull request by lchayoun**

### CODE REVIEW

**Comment by marcosbarbero** [comment]
thanks again @lchayoun, I'll try to delivery this new version somewhere in today's noon.

**Comment by lchayoun** [comment]
Thank you! great code base

**Comment by marcosbarbero** [comment]
Thank you for helping me to improve!

**Comment by marcosbarbero** [comment]
@lchayoun here it goes [v1.3.0.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v1.3.0.RELEASE) also available at maven central

**Pull request merged**
