### PR TITLE
Fixed issue 160 so that it only applies one limit per request.

### LINKED ISSUE #160: Is it possible to whitelist certain IP addresses?
I have already implemented the rate limiting in my project. However, I have a specific IP address that will be making many requests and I don't want to limit it from making calls. Ideally I would like to be able to input a list of IP addresses that don't get rate limited. Is this at all possible currently? I am using Consul repository if that matters at all.

### PR DESCRIPTION
**Pull request by andrew-holman**
Fixes #160 

#### Changes proposed in this pull request:
 - Adds the ability to only apply one limit per request.
 - Also adds the variable breakOnMatch that can be set to enable to disable this change, as a default the change is be disabled.

### CODE REVIEW

**Comment by marcosbarbero** [comment]
Hi @andrew-holman thanks for your contribution, may I ask you to add this new property to the README file? :)

**Comment by andrew-holman** [comment]
Let me know if you think I need to make any more changes.

**Comment by andrew-holman** [comment]
Just let me know if there is anything I can do to help the review process along.

**Comment by marcosbarbero** [comment]
Hi @andrew-holman sorry for this long delay, I just merged it and will release a new version later today.

**Comment by andrew-holman** [comment]
Okay, thanks so much! I'm currently using the 1.7.x branch, will that be updated with this change as well?

**Comment by marcosbarbero** [comment]
If you have spare time to do that would be great!

**Pull request merged**
