### PR TITLE
#112 Remove InMemory implementation

### LINKED ISSUE #112: Remove InMemory implementation
Since we support bucket4j, and it has in memory caches support, out InMemory implementation is not necessary and it is also dangerous since it can't be limited in size

### PR DESCRIPTION
**Pull request by lchayoun**
Fixes #112

### CODE REVIEW

**Comment by marcosbarbero** [comment]
The changes look nice, just a question. There will be a default implementation like `IN_MEMORY` was?

**Comment by lchayoun** [comment]
I didn't specified a default, not sure what default will be good, I think that an implementation should be specified.

**Comment by marcosbarbero** [comment]
Fine by me, maybe we should specify it in the README file? Also bump the version to `2.1.0`, WDYT?

**Comment by lchayoun** [comment]
bumped the version and fixed the documentation

**Comment by lchayoun** [comment]
@marcosbarbero please merge :)

**Pull request merged**
